{{- $sourceSecret := .Values.build.sourceSecret | default dict -}}
{{- if ($sourceSecret.create | default false) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.build.git.sourceSecret | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeoptix-reporter.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ $sourceSecret.username | default "x-access-token" | quote }}
  password: {{ required "build.sourceSecret.token é obrigatório quando build.sourceSecret.create=true" $sourceSecret.token | quote }}
{{- end }}
