{{- if .Values.deploy.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kubeoptix-reporter.fullname" . }}
  labels:
    {{- include "kubeoptix-reporter.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "kubeoptix-reporter.selectorLabels" . | nindent 6 }}
{{- end }}
