O {cust} (Departamento de Trânsito do Distrito Federal) é uma autarquia do Governo do Distrito Federal responsável pela gestão do trânsito no território distrital.
Entre suas atribuições estão os serviços de habilitação de condutores (CNH), registro e licenciamento de veículos, fiscalização, educação para o trânsito e promoção da segurança viária.
A Red Hat Consulting foi selecionada pelo {cust} para definir uma arquitetura com Developer Hub voltada à integração de pipelines e à implantação de uma IDP (Internal Developer Platform). Este documento apresenta um estudo do ambiente atual e propõe evoluções para sua implementação.

= Pré-requisitos

* Usuário com perfil de acesso `admin` aos consoles web dos clusteres OpenShift.
* Acesso leitura a todos os grupos e subgrupos do gitlab.

**Cluster Hub**

* Console web: https://console-openshift-console.apps.ocpmgt.detran.df/


**Cluster HML/DEV**

* Console web: https://console-openshift-console.apps.ocpnoprod.detran.df/


**Cluster PRD**

* Console web: https://console-openshift-console.apps.ocpprod.detran.df/


* Acesso aos repositórios git.

* URLs dos repositórios: https://gitlab.detran.df.gov.br/
