////
Propósito
-------
Esta seção deve fornecer recomendações que não estão diretamente relacionadas a
as tecnologias implantadas por esse trabalho ou treinamento relacionado (cada coisa em seu lugar). 
Um dos principais objetivos da Red Hat Services é obter o status de "trusted advisor" com cada cliente.

Candidatos a recomendação:
- Sugestões organizacionais e/ou políticas 
- Oportunidades de modernização
- Recomendações de atualização (upgrade)
- Melhorias gerais de segurança (não específicas dos produtos entregues)


Exemplo
-------
== Credenciais da Conta de Serviço vs. Credenciais Pessoais
=== Indicação
O CloudForms possui um requisito documentado para uma conta administrativa irrestrita a nível root para gerenciar adequadamente o VMware. {{cust}} optou por usar uma conta de serviço de acesso limitado para o CloudForms, citando preocupações de segurança e uma política de segurança interna destinada a controlar contas de usuários individuais.

=== Recomendação
Crie uma política de segurança específica para ferramentas de automação, como o CloudForms, diferente de uma política de segurança destinada a controlar contas de usuários pessoais.

== Ansible Vault
=== Indicação
Enquanto a configuração da Ansible Tower estava fora do escopo desse trabalho com o RHV, observou-se que os playbooks estavam sendo criados com senhas em texto simples em linha (clear text).

=== Recomendação
Considere implementar o Ansible Vault para proteger as senhas.

== Programa "Automation Adoption"
=== Indicação
Embora a automação não fizesse parte dessa entrega, vários desafios encontrados foram relacionados ao tempo de resposta necessário para obter as atualizações executadas manualmente por meio de scripts BASH.
=== Recomendação
Muitos dos desafios que {{cust}} parecem enfrentar podem ser atenuados pela introdução de uma plataforma de automação como a Ansible. Considere conversar com seu representante Red Hat sobre o programa "Automation Adoption", pois acreditamos que cairia bem nesse caso.
////

#TODO#
