////
Propósito
-------
No mínimo, a data de criação inicial deve ser registrada. Antes de compartilhar com o cliente é necessário sempre atualizar essa sessão do documento.

As versões de documentos são análogas as publicações e devem ser usadas apenas para
descrever progresso ou atualizações significativas e não correções ou correções menores. 
Por exemplo, não seria apropriado publicar uma nova versão
sempre que o diário (daily journal) é atualizado.

Tente manter-se dentro do intervalo de três e dez revisões. No entanto, cada
projeto tem diferentes necessidades potenciais em termos de documentação, portanto,
bom senso deve ser usado se um número maior de revisões for necessário.

Para simplificar, é recomendável que cada versão seja representada por um
número inteiro (ou seja, 1, 2, 3, etc ...) com a criação inicial sendo a versão '0'.

As alterações listadas para cada versão devem incluir a conclusão das seções principais,
adições e atualizações solicitadas pelo cliente.

#TODO#
////
.Revisões do documento
[cols="1,2,5",options=header]
|===
|Versão
|Data
|Alterações

// Versão
| 0

// Data
| #TODO#

// Alterações
a|
- Elaboração do documento


// Versão
| #TODO#

// Data
| #TODO#

// Alterações
a|
- #TODO#
- #TODO#

|===