////
Purpose
-------

To describe what navigate is and does, how to use it and subsequently include it.


Sample
------

////
Navigate é uma estrutura orientada à experiência da Red Hat® Consulting que ajuda os clientes a entender, planejar e avançar para a adoção bem-sucedida das tecnologias Red Hat.

Independentemente do estágio de implementação atual de um projeto de modernização, um compromisso do Navigate alinha as metas de transformação digital existentes e futuras de um cliente com as tecnologias da Red Hat.

O Navigate começa com uma avaliação que estabelece o contexto do cliente nas áreas de estratégia de negócios e cenário tecnológico. Arquitetos experientes da Red Hat realizam uma série de workshops cobrindo tópicos técnicos e de negócios para ajudar os clientes a obter o melhor valor dos produtos e tecnologias da Red Hat.

Um compromisso do Navigate oferece maneiras para os clientes usarem a tecnologia de código aberto da Red Hat para atingir suas prioridades e metas de negócios definidas. Os arquitetos e consultores da Red Hat ajudam os clientes a criar um envolvimento em fases baseado em sprint para desenvolver uma plataforma fundamental como um campo de provas para recursos e operações de TI.


include::navigate-report.adoc[opts=optional]
