////
Objetivo
-------

Esta seção serve como um preâmbulo para o Relatório de Engajamento de Consultoria.

Direitos autorais, confidencialidade e isenção de responsabilidade têm implicações legais a o redação até agora estabelecida foi revisada e aprovada pelo Departamento jurídico.  Não altere os títulos povoados desta seção sem aprovação do legal.

Sample
------
N/A

////

= Prefácio

== Confidencialidade e Isenção de Responsabilidade
Este é um documento voltado para a Red Hat, Inc. e {customer} ("Cliente").

Este Consulting Engagement Report (CER) contém Informações Confidenciais da Red Hat e Informações Confidenciais do Cliente, sujeitas aos termos de confidencialidade do contrato que rege os Serviços prestados pela Red Hat.

== Público
Este documento é destinado à equipe técnica do Cliente responsável pelo ambiente.

== Background Adicionais e Documentos Relacionados
Este documento não contém detalhes passo a passo da instalação ou de outras tarefas, pois são abordados na documentação relevante no link:https://access.redhat.com/[]. Links para os documentos apropriados serão feitos quando necessário.

== Scripts e playbooks
Todos os scripts fornecidos estão sendo fornecidos _as-is_, sem qualquer forma de suporte ou garantia. +
Todos os scripts fornecidos podem ser modificados pelo cliente conforme necessidade.

== _Customer Satisfaction Survey_ (CSat)
A Red Hat está comprometida com a qualidade da experiência do cliente e com a melhoria contínua de nossos serviços. Seus comentários são o fator mais importante para determinar se atendemos às suas expectativas e o que podemos fazer para melhorar. Você receberá uma pesquisa de satisfação do cliente ao concluir nosso projeto. Reserve alguns minutos para nos fornecer um feedback sincero da sua experiência. Enquanto isso, se houver qualquer preocupação ou problemas no projeto, não hesite em entrar em contato com o {rhprojectmanager}.
