deploy:
  enabled: true

nameOverride: ""
fullnameOverride: ""

build:
  enabled: true
  git:
    uri: https://github.com/ShiftWise-AI/kubeoptix-reporter.git
    ref: main
    sourceSecret: github-auth
  sourceSecret:
    create: false
    username: x-access-token
    token: ""
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi

image:
  useBuildOutput: true
  repository: quay.io/parraes/kubeoptix-reporter
  tag: 1.0.0
  pullPolicy: Always

service:
  api:
    enabled: true
    name: reporter-api
    type: ClusterIP
    port: 8000
    targetPort: 8000

scalePolicy:
  enabled: true
  maxReplicas: 1

podEnv:
  TZ: America/Sao_Paulo
  LOG_LEVEL: INFO

persistence:
  enabled: true
  existingClaim: harvester-app-data
  mountPath: /app/data
  reportsPath: /app/data/reports

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  startup:
    failureThreshold: 30
    periodSeconds: 2
  readiness:
    initialDelaySeconds: 2
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 20
    timeoutSeconds: 2
    failureThreshold: 3
