// Este arquivo é mantido executando scripts/refresh-training.py script

= Python Programming with Red Hat (AD141)

[.big]#*Descrição do curso*#

*Programação em Python para iniciantes*

O Python é uma linguagem de programação muito famosa entre os administradores de sistema, cientistas de dados e desenvolvedores. Ele é usado para criar aplicações web e módulos personalizados do Red Hat Ansible Automation, além de realizar análises estatísticas e treinar modelos de inteligência artificial e machine learning. Neste curso, você vai aprender sobre a linguagem Python e ver conceitos básicos como fluxo de controle, loops, estruturas de dados, funções, E/S de arquivos, expressões regulares, análise de JSON e depuração. Este curso é baseado no Python 3 e no RHEL 9.0.

Após a conclusão do curso, o acesso prático ao laboratório permanecerá disponível por até 45 dias para qualquer curso presencial que inclua um ambiente virtual.

*Observação*: 

Este curso é oferecido nos seguintes formatos: presencial (quatro dias), aula virtual (cinco dias) ou online (individualizado).As durações podem variar de acordo com a entrega. Para conferir todos os detalhes, a programação e os preços do curso, selecione a localização e clique em "Registre-se" no menu à direita.

[.big]#*Resumo do conteúdo*#

* Noções básicas sobre sintaxe, funções e tipos de dados do Python

* Depuração de scripts Python usando o depurador da linguagem (pdb)

* Uso de estruturas de dados Python, como dicionários, conjuntos, tuplas e listas para lidar com dados compostos

* Noções sobre programação orientada a objetos em Python e como lidar com exceções

* Leitura e gravação de arquivos em Python, além da análise de dados JSON

* Uso de expressões regulares avançadas em Python para manipular texto

* Estruturação eficiente de grandes programas Python usando módulos e namespaces

* Uso de bibliotecas de terceiros por meio da ferramenta de interface de linha de comando (CLI) pip


[.big]#*Público-alvo*#

* Administradores de sistema e profissionais de DevOps que queiram usar o Python para automatizar as tarefas do sistema operacional

* Desenvolvedores de outras linguagens de programação que queiram aprender sobre o Python para escrever aplicações

* Profissionais de inteligência artificial e machine learning, cientistas de dados e engenheiros que queiram usar o Python na análise de dados e machine learning


[.big]#*Pré-requisitos*#

* Não há pré-requisitos para este curso.


[.big]#*Requisitos técnicos*#

* Para aprendizado virtual, em ritmo próprio, ou treinamento presencial:
** É necessário ter acesso à internet.
** Os laboratórios são realizados no ambiente de aprendizado online da Red Hat.
** Para treinamento presencial, a Red Hat fornecerá um ambiente de curso instalado localmente como alternativa no futuro.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/ad141-red-hat-training-presents-introduction-to-python-programming
