// Este arquivo é mantido executando scripts/refresh-training.py script

= Red Hat JBoss Application Administration I (AD248)

[.big]#*Descrição do curso*#

*Instale, configure e gerencie o Red Hat JBoss Enterprise Application Platform*

No curso Red Hat JBoss Application Administration I, você aprenderá as práticas recomendadas para a instalação e a configuração do https://www.redhat.com/pt-br/technologies/jboss-middleware/application-platform-old[Red Hat® JBoss® Enterprise Application Platform (JBoss EAP) 7]. Por meio de laboratórios hands-on, aprenda as principais tarefas que um administrador de sistemas precisa saber para implantar e gerenciar de forma eficiente aplicações no JBoss EAP.

Este curso é baseado no Red Hat JBoss® Enterprise Application Platform 7.4.

Após a conclusão do curso, o acesso prático ao laboratório permanecerá disponível por até 45 dias para qualquer curso presencial que inclua um ambiente virtual.

[.big]#*Resumo do conteúdo*#

* Instalação e execução do JBoss EAP 7 nos modos autônomo e de domínio
* Configuração e gerenciamento de um domínio do JBoss EAP
* Implantação de aplicações no JBoss EAP 7 nos modos autônomo e de domínio
* Configuração do subsistema da fonte de dados
* Configuração do Java^™^ Message Service (JMS)
* Configuração do subsistema de registros
* Configuração do subsistema da web
* Implementação da segurança de aplicações no JBoss EAP 7
* Configuração e ajuste da JVM para o JBoss EAP
* Agrupamento em cluster das instâncias do JBoss EAP

[.big]#*Público-alvo*#

Administradores de sistemas iniciantes no Red Hat JBoss ou com experiência no Red Hat JBoss Enterprise Application Platform 7.

[.big]#*Pré-requisitos do curso*#

* https://skills.ole.redhat.com/en[Faça nossa avaliação gratuita] para saber se esta é a melhor opção para suas habilidades.
* Experiência básica com administração dos sistemas operacionais Microsoft Windows, UNIX ou Linux^®^
* .Compreensão básica da rede TCP/IP
* Não é necessário ter conhecimento prévio de Java ou scripts de shell

[.big]#*Requisitos técnicos*#

* Para aprendizado virtual, em ritmo próprio, ou treinamento presencial:
** É necessário ter acesso à internet.
** Os laboratórios são realizados no ambiente de aprendizado online da Red Hat.
** Para treinamento presencial, a Red Hat fornecerá um ambiente de curso instalado localmente como alternativa no futuro.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/ad248-red-hat-jboss-application-administration-i
