// Este arquivo é mantido executando scripts/refresh-training.py script

= MLOps Enablement with Red Hat OpenShift AI (AI500)

[.big]#*Descrição do curso*#

*Experimente as possibilidades do MLOps com práticas e cultura open source comprovadas, usadas pela Red Hat para oferecer suporte à inovação do cliente.*

* O MLOps Practices with Red Hat OpenShift AI (AI500) é um curso imersivo de cinco dias que oferece aos participantes a oportunidade de vivenciar e implementar uma jornada bem-sucedida de adoção de MLOps. Muitos programas de treinamento em IA ou ciência de dados se concentram em um determinado framework ou tecnologia, mas este curso mostra como as melhores ferramentas open source se encaixam em um fluxo de trabalho completo de MLOps. Ele combina descoberta, treinamento e entrega contínuos em uma experiência altamente envolvente que simula cenários reais de machine learning.
* Para atingir os objetivos de aprendizagem, os participantes devem incluir pessoas com funções diferentes na organização. Cientistas de dados, engenheiros de machine learning, engenheiros de plataforma, arquitetos e product onwers ganharão experiência trabalhando além dos silos tradicionais. A rotina diária simula uma equipe de entrega do mundo real, na qual equipes multifuncionais aprendem como a colaboração gera inovação. Com as experiências compartilhadas e as práticas recomendadas, a equipe pode aplicar o que aprendeu para a cultura e a missão da empresa darem certo, com o objetivo de buscar novos projetos e processos aprimorados.
* Este curso é baseado no Red Hat OpenShift AI, no Red Hat OpenShift GitOps e na IA preditiva

*Observação:* este curso é oferecido como cinco aulas presenciais ou como cinco aulas virtuais. A duração do curso pode variar de acordo com o formato escolhido. Para conferir todos os detalhes, a programação e os preços do curso, selecione a localização e clique em "Enviar" no menu à direita.

[.big]#*Resumo do conteúdo do curso*#

* Este curso abrange a jornada completa de um caso de uso de aplicação inteligente preditiva, da ideia à experimentação interna e produção, enquanto reúne diferentes personas para colaborar de forma simplificada em uma única plataforma.
* Este curso combina práticas culturais e técnicas em uma experiência única e altamente envolvente, repleta de aplicações reais. Você aprenderá as práticas de MLOps e como elas se complementam para melhorar o alinhamento da equipe e a eficiência da entrega.
* A maior parte do treinamento em IA se concentra em um determinado framework ou tecnologia. Este curso combina as melhores ferramentas open source enquanto oferece a experiência de como elas se combinam para criar, implantar e manter modelos de IA em produção com confiança e eficiência.

[.big]#*Público-alvo*#

Essa experiência demonstra como indivíduos em diferentes funções devem aprender a compartilhar, colaborar e trabalhar em prol de um objetivo comum para alcançar resultados positivos e impulsionar a inovação.

Ela é importante principalmente para:

* *Usuários de plataformas MLOps*: cientistas e engenheiros de dados e desenvolvedores de aplicações.
* *Provedores de plataforma MLOps*: engenheiros de machine learning, de MLOps e de plataforma.
* *Stakeholders da plataforma MLOps*: arquitetos e gerentes de TI.

O cenário incorpora aspectos técnicos do trabalho com sistemas de machine learning, oferecendo insights práticos sobre como essas pessoas podem alinhar seus esforços.

Você aprenderá como agregar valor continuamente aos clientes acelerando a implantação de novos modelos no mercado. Nossos instrutores compartilharão experiências e práticas recomendadas aprendidas no contato direto com os clientes durante a prestação de serviços da Red Hat.

[.big]#*Pré-requisitos do curso*#

* https://skills.ole.redhat.com/en[Faça nossa avaliação gratuita] para saber se esta é a melhor opção para as suas habilidades.
* https://www.redhat.com/pt-br/services/training/do080-deploying-containerized-applications-technical-overview[Containers, Kubernetes and Red Hat OpenShift Technical Overview (DO080)] ou ter conhecimento básico sobre OpenShift/Kubernetes e containers é útil
* Ter conhecimento avançado sobre IA ouhttps://docs.redhat.com/en/ai-foundations[Red Hat AI Foundations]é vantajoso

[.big]#*Requisitos técnicos*#

* Este curso exige acesso à Internet para entrar no ambiente de cluster compartilhado.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/ai500-mlops-enablement-red-hat-openshift-ai
