// Este arquivo é mantido executando scripts/refresh-training.py script

= Red Hat OpenStack Technical Overview (CL010)

[.big]#*Descrição do curso*#

*Uma visão geral do Red Hat OpenStack Platform.*

O Red Hat OpenStack Technical Overview (CL010) é uma série de vídeos online que ajudará você a compreender melhor os conceitos básicos de cloud computing e do Red Hat^®^ OpenStack^®^ Platform. Estão incluídos vários casos de uso, além de demonstrações online.

Este curso está disponível em inglês (inclusive com legenda closed caption), japonês, francês, alemão, chinês, espanhol, coreano e italiano.

[.big]#*Resumo do curso*#

Com vídeos online, sob demanda, você aprenderá sobre:

* Cloud computing
* Red Hat OpenStack Platform 
* Computação, armazenamento e rede em relação ao Red Hat OpenStack Platform
* Alta disponibilidade com o Red Hat OpenStack Platform
* Implantação do Red Hat OpenStack Platform

*Observação:* você pode assistir a todos os vídeos ou apenas aos que forem de seu interesse. Não há laboratórios hands-on nem reconhecimento de conclusão associados a este curso.

[.big]#*Público-alvo*#

Líderes, administradores, engenheiros, arquitetos de TI e qualquer outra pessoa que queira adquirir conhecimento geral sobre os recursos do Red Hat OpenStack Platform.

[.big]#*Pré-requisitos*#

Não há pré-requisitos para este curso.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/cl010-red-hat-openstack-technical-overview
