// Este arquivo é mantido executando scripts/refresh-training.py script

= OpenStack Administration: Control Plane Management (CL170)

[.big]#*Descrição do curso*#

*Use o Red Hat OpenShift para gerenciar os serviços do OpenStack e nós de computação do RHEL que executam cargas de trabalho baseadas em VM.*

O OpenStack Administration: Control Plane Management (CL170) ajuda os administradores de clusters do Red Hat OpenStack a gerenciar a integridade e o desempenho dos serviços de control plane do OpenStack, solucionar problemas com a inspeção de operadores e cargas de trabalho do Kubernetes e configurar serviços de control plane do OpenStack usando recursos personalizados do Kubernetes.

Este curso é baseado no Red Hat OpenShift Services on OpenStack 18.

*Observação:* este curso é oferecido como duas aulas presenciais e três aulas virtuais ou no ritmo que você preferir. A duração pode variar com base no formato escolhido. Para conferir todos os detalhes, a programação e os preços do curso, selecione a localização e clique em "Registre-se" no menu principal.

[.big]#*Resumo do conteúdo do curso*#

* Verificar a integridade dos operadores e cargas de trabalho do OpenStack e identificar serviços desabilitados ou configurados incorretamente
* Coletar informações de solução de problemas de control e data planes do OpenStack para solicitações de suporte ao cliente
* Habilitar e personalizar os serviços de control plane do OpenStack configurando o recurso personalizado de control plane
* Verificar a integridade das notas de computação do OpenStack e identificar serviços de data plane ausentes ou configurados incorretamente
* Remover e substituir ou reprovisionar os nós de computação com falha

[.big]#*Público-alvo*#

* Engenheiros de plataforma, administradores de nuvem e administradores de sistema interessados em gerenciar, ajustar e solucionar problemas de clusters do Red Hat OpenStack

[.big]#*Pré-requisitos do curso*#

* https://www.redhat.com/rhtapps/assessment/[Faça nossa avaliação gratuita] para saber se esta é a melhor opção para suas habilidades
* É recomendado fazer o https://www.redhat.com/pt-br/services/training/rh124-red-hat-system-administration-i[Red Hat System Administration I (RH124)]
* Recomendado, mas não obrigatório: https://www.redhat.com/pt-br/services/training/rh134-red-hat-system-administration-ii[Red Hat System Administration II (RH134)] e https://www.redhat.com/pt-br/services/training/rh294-red-hat-linux-automation-with-ansible[Red Hat Enterprise Linux Automation with Ansible (RH294)] ou demonstrar habilidades equivalentes
* https://www.redhat.com/pt-br/services/training/red-hat-openshift-administration-i-operating-a-production-cluster[Red Hat OpenShift Administration I: Operating a Production Cluster (DO180)] ou demonstrrar habilidades equivalentes
* Conceitos básicos para o armazenamento de data center: protocolos de armazenamento, NAS e SAN
* Conceitos para rede do data center: modelo ISO, VLANs, firewalls e protocolos de Internet, incluindo ICMP, IP e HTTP, entre outros
* Conceitos básicos para o armazenamento de objetos, como experiência com AWS S3, são desejados, mas não obrigatórios
* Habilidades de administração do Ceph são desejadas, mas não obrigatórias

[.big]#*Requisitos técnicos*#

* Para aprendizado virtual, em ritmo próprio, ou treinamento presencial:
** É necessário ter acesso à internet.
** Os laboratórios são realizados no ambiente de aprendizado online da Red Hat.
** Para treinamento presencial, a Red Hat fornecerá um ambiente de curso instalado localmente como alternativa no futuro.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/cl170-openstack-administration-control-plane-management
