// Este arquivo é mantido executando scripts/refresh-training.py script

= Red Hat OpenStack Administration II: Day 2 Operations for Cloud Operators (CL210)

[.big]#*Descrição do curso*#

*Desenvolva habilidades avançadas para realizar operações do Dia 2 no Red Hat OpenStack Platform e gerenciar a infraestrutura de nuvem híbrida*

O Red Hat OpenStack Administration II: Day 2 Operations for Cloud Operators (CL210) foi desenvolvido para operadores de nuvem, administradores de serviços e engenheiros de automação que operam e gerenciam um ambiente de computação em nuvem privada e híbrida com todos os recursos usando o Red Hat OpenStack Platform. Você aprenderá a gerenciar, monitorar, solucionar problemas e escalar uma infraestrutura do Red Hat OpenStack Platform. Este curso tem como foco o uso da interface de usuário da linha de comando do OpenStack Client para configurar métricas, políticas e arquitetura em suporte a aplicações em nuvem empresarial e operações diárias.

Este curso é baseado no Red Hat OpenStack versão 16.1 e Red Hat Enterprise Linux versão 8.2

Após a conclusão do curso, o acesso prático ao laboratório permanecerá disponível por até 45 dias para qualquer curso presencial que inclua um ambiente virtual.

*Observação:* esse curso é oferecido como uma aula virtual de cinco dias ou no ritmo que você preferir. As durações podem variar de acordo com a entrega. Para conferir todos os detalhes, a programação e os preços do curso, selecione a localização e clique em "Registre-se" no menu à direita.

[.big]#*Resumo do conteúdo*#

* Gerenciamento da tecnologia de conteinerização de serviços overcloud.
* Disponibilização de métricas para ajuste de desempenho e governança.
* Monitoramento e solução de problemas de fluxo de rede do Open Virtual Networking (OVN).
* Configuração do serviço de identidades usando um armazenamento externo do Red Hat IdM.
* Gerenciamento do control plane principal, incluindo o Pacemaker.
* Personalização de imagens com técnicas para vários casos de uso.
* Gerenciamento de back-ends de armazenamento em blocos e objetos.
* Gerenciamento de nós de computação, incluindo ajuste e hiperconvergência.
* Solução de problemas do Red Hat OpenStack Platform.

[.big]#*Público-alvo*#

* Operadores de nuvem responsáveis por gerenciar automações e operações diárias.
* Arquitetos de infraestrutura interessados ou responsáveis por manter uma nuvem híbrida ou privada em grande escala.

[.big]#*Pré-requisitos do curso*#

* Ter a certificação https://www.redhat.com/pt-br/services/certification/rhce[Red Hat Certified Engineer (RHCE)], https://www.redhat.com/pt-br/services/certification/rhcs-ansible-automation[Red Hat Certified Specialist in Ansible Automation] ou demonstrar experiência equivalente.
* Os candidatos que não tiverem a certificação RHCE ou equivalente podem verificar se possuem as habilidades e os conhecimentos necessários por meio da https://skills.ole.redhat.com/[nossa avaliação gratuita] e ver se esta é a melhor opção com base nos resultados.
* Concluir o curso https://www.redhat.com/pt-br/services/training/cl110-red-hat-openstack-administration-i[Red Hat OpenStack Administration I: Core Operations for Domain Operators (CL110)] ou demonstrar experiência equivalente.

[.big]#*Requisitos técnicos*#

* Para aprendizado virtual, em ritmo próprio, ou treinamento presencial:
** É necessário ter acesso à internet.
** Os laboratórios são realizados no ambiente de aprendizado online da Red Hat.
** Para treinamento presencial, a Red Hat fornecerá um ambiente de curso instalado localmente como alternativa no futuro.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/cl210-red-hat-openstack-administration
