// Este arquivo é mantido executando scripts/refresh-training.py script

= Introdução ao Red Hat OpenShift Service on AWS (CS120)

[.big]#*Descrição do curso*#

*Aprenda a implantar, acessar e realizar operações diárias em um cluster do ROSA.*

Este curso ensina a equipe de operações de TI a implantar um cluster público do Red Hat OpenShift Service on AWS (ROSA), oferecendo experimentação e provisionamento de projetos nos quais as equipes de desenvolvimento possam trabalhar. A equipe de operações de TI aprenderá como realizar operações diárias dos clusters do ROSA e oferecer suporte às equipes de aplicações que o utilizam. Assim, a equipe de operações de TI pode aplicar as mesmas habilidades e procedimentos semelhantes nos clusters privados do ROSA nas organizações.

[.big]#*Resumo do conteúdo do curso*#

* Introdução ao OpenShift gerenciado
* Identificar pré-requisitos para criar e implantar um cluster do ROSA
* Acessar um cluster do ROSA como administrador
* Configurar a autenticação do GitHub
* Conectar clusters do ROSA aos serviços em nuvem da Red Hat
* Configurar projetos com medidas de segurança para equipes de aplicações
* Provisionamento e configuração declarativos de projetos usando o OpenShift GitOps
* Realizar atualizações de versão do OpenShift
* Limpar recursos da AWS de clusters excluídos

[.big]#*Público-alvo*#

* *Principal:*
** Administradores do ROSA
** Administradores de sistema, engenheiros de plataforma, engenheiros de nuvem, outras funções de TI relacionadas à infraestrutura que são responsáveis pelo suporte e provisionamento da infraestrutura de aplicações implantadas na AWS.
* *Secundário:*
** Arquitetos empresariais
** Profissionais de infraestrutura de aplicações e desenvolvimento, como engenheiros de confiabilidade de sites e de DevOps.

[.big]#*Treinamentos recomendados*#

* Todos os alunos precisam conhecer a Amazon Web Services (AWS), incluindo a operação e o gerenciamento dos recursos de computação, armazenamento e rede da AWS
* No caso dos alunos sem experiência no Red Hat OpenShift, o recomendado é aprender as habilidades básicas de gerenciamento de clusters do Red Hat OpenShift usando os seguintes cursos: 
** https://www.redhat.com/pt-br/services/training/red-hat-openshift-administration-i-operating-a-production-cluster?sc_cid=7013a000003BknRAAS[Red Hat OpenShift I: Containers & Kubernetes (DO180)]
** https://www.redhat.com/pt-br/services/training/red-hat-openshift-administration-ii-configuring-a-production-cluster[Red Hat OpenShift Administration II: Operating a Production Kubernetes Cluster (DO280)]
* Recomendamos aos alunos com experiência no gerenciamento de clusters do Kubernetes que façam os cursos DO180 e DO280, ou que aprendam pelo menos as habilidades básicas para operar os clusters do Red Hat OpenShift. Para isso, a Red Hat disponibiliza os seguintes recursos gratuitos: 
** https://developers.redhat.com/developer-sandbox[Sandbox do Red Hat Developer para o OpenShift]
** https://developers.redhat.com/learn/openshift[Conhecimentos do Red Hat Developer sobre OpenShift e Kubernetes]
** https://www.redhat.com/pt-br/services/training/do080-deploying-containerized-applications-technical-overview[Containers, Kubernetes and Red Hat OpenShift Technical Overview (DO080)]

[.big]#*Requisitos técnicos*#

* A conexão com a Internet é necessária para acessar os serviços da AWS por meio do portal ou da interface de linha de comando (CLI) dessa plataforma. Você também precisará acessar o console de nuvem híbrida da Red Hat e os serviços em nuvem associados da Red Hat.
* Os alunos precisam ter uma conta ativa da AWS com permissão para ativar os serviços do AWS Marketplace e um método de pagamento associado. Isso é necessário devido aos recursos da AWS que são consumidos pelos clusters do ROSA.
* Os alunos precisam ter uma conta ativa no Portal do Cliente Red Hat ou uma https://developers.redhat.com/about[assinatura gratuita do programa Red Hat Developer]

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/cs120-introduction-red-hat-openshift-service-on-aws
