// Este arquivo é mantido executando scripts/refresh-training.py script

= Creating and Configuring Production ROSA Clusters (CS220)

*Crie e configure clusters do ROSA no nível de produção como parte da área de ocupação maior de um cliente da AWS.*

[.big]#*Descrição do curso*#

O curso Creating and Configuring Production ROSA Clusters (CS220) ensina a configurar clusters do ROSA como parte de ambientes preexistentes da AWS e a integrar o ROSA aos serviços da AWS normalmente usados por equipes de operações de TI, como o Amazon CloudWatch.

*Observação:* esse curso é oferecido como duas aulas presenciais, e três aulas virtuais ou no ritmo que você preferir. A duração pode variar de acordo com a entrega. Para conferir todos os detalhes, a programação e os preços do curso, selecione a localização e clique em "Registre-se" no menu à direita.

[.big]#*Resumo do conteúdo do curso*#

* Criar clusters do ROSA pelo PrivateLink com STS
* Conectar clusters do ROSA pelo PrivateLink às VPCs existentes e permitir que administradores e desenvolvedores acessem esses clusters
* Configurar pools de máquina dedicados e escalabilidade automática de nós/pods
* Configurar encaminhamento de log de auditoria, cluster e nó para o Amazon CloudWatch
* Configurar autenticação e sincronização de grupo com o Amazon Cognito

[.big]#*Público-alvo*#

* Engenheiros de plataforma, administradores de nuvem, administradores de sistema e outras funções de TI relacionadas à infraestrutura que são responsáveis pelo suporte e provisionamento da infraestrutura de aplicações implantadas na AWS.
* Arquitetos empresariais, engenheiros de confiabilidade de sites, engenheiros de DevOps e outras funções de TI relacionadas a aplicações que são responsáveis por projetar a infraestrutura de aplicações implantadas na AWS.

[.big]#*Treinamentos recomendados*#

* https://www.redhat.com/pt-br/services/training/cs120-introduction-red-hat-openshift-service-on-aws[]*CS120 - Introduction to Red Hat OpenShift Service on AWS* ou experiência equivalente: "Sei como criar e acessar um cluster público do ROSA".
* Administração da AWS com nível de *AWS Certified SysOps Administrator - Associate* ou *AWS Certified Solutions Architect - Associate* ou experiência equivalente: "Sei gerenciar os serviços de infraestrutura da AWS".
* Conhecimento básico em OpenShift pelo https://www.redhat.com/pt-br/services/training/do080-deploying-containerized-applications-technical-overview[]*DO080 Technical Overview:* "Conheço os conceitos básicos do OpenShift e containers".

[.big]#*Requisitos técnicos*#

* Para aprendizado virtual, em ritmo próprio, ou treinamento presencial:
** É necessário ter acesso à internet.
** Os laboratórios são realizados no ambiente de aprendizado online da Red Hat.
** Para treinamento presencial, a Red Hat fornecerá um ambiente de curso instalado localmente como alternativa no futuro.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/creating-and-configuring-production-rosa-clusters-cs220
