// Este arquivo é mantido executando scripts/refresh-training.py script

= Ansible Basics: Automation Technical Overview (DO007)

[.big]#*Descrição do curso*#

*Crie, escale e gerencie automação com o Red Hat Ansible Automation Platform*

* Ansible Basics: Automation Technical Overview é uma série de vídeos sob demanda que apresentam o Red Hat Ansible Automation Platform. Aprenda a fazer o gerenciamento de configuração, o provisionamento, a implantação e o gerenciamento da infraestrutura computacional com o Ansible em ambientes físicos, virtuais e de nuvem.

[.big]#*Resumo do conteúdo do curso*#

* No curso Ansible Automation Technical Overview, você aprenderá a usar o Ansible para simplificar tarefas de TI, como gerenciamento de configurações, implantação de aplicações e orquestração. Ministrado por Roger Lopez, gerente de marketing técnico em Ansible, este curso introdutório abrange conceitos essenciais do Ansible, incluindo módulos, tarefas e playbooks. Por meio de exemplos reais, você explorará como o Automation Controller se encaixa nos fluxos de trabalho de automação e como o Ansible Automation Platform pode ser usado para gerenciar ambientes de produção.
* Este curso é baseado no Ansible Automation Platform 2.5

[.big]#*Público-alvo do curso*#

* Arquitetos, engenheiros, administradores, líderes de TI, entre outros profissionais que desejam se aprofundar no Ansible

[.big]#*Treinamentos recomendados*#

* Não há pré-requisitos para esta visão geral técnica.

[.big]#*Requisitos técnicos*#

* N/D

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/do007-ansible-essentials-simplicity-automation-technical-overview
