// Este arquivo é mantido executando scripts/refresh-training.py script

= Visão geral técnica do Red Hat OpenShift Virtualization (DO016)

[.big]#*Descrição do curso*#

*Comece seu treinamento em Red Hat OpenShift Virtualization gratuitamente.*

Junte-se a Andrew Sullivan, gerente sênior, marketing técnico, para uma visão geral técnica do Red Hat OpenShift Virtualization. Ao longo da série de vídeos sob demanda, os estudantes ganharão conhecimento prático sobre a criação de máquinas virtuais, seu gerenciamento, configuração de rede, garantia de alta disponibilidade e migração eficiente de máquinas virtuais existentes para o OpenShift Virtualization.

[.big]#*Resumo do conteúdo do curso*#

* Introdução à visão geral técnica
* Criação e gerenciamento de máquinas virtuais
* Redes de host e VM
* Armazenamento de máquina virtual
* Gerenciamento bare metal e alta disponibilidade
* Kit de ferramentas de migração para máquinas virtuais
* Próximas etapas para continuar o treinamento

[.big]#*Público do curso*#

* Administradores de máquinas virtuais interessados em mover cargas de trabalho virtualizadas dos hipervisores tradicionais para o OpenShift Virtualization.
* Administradores do Kubernetes (administradores de clusters, engenheiros de clusters) com interesse em oferecer suporte a cargas de trabalho virtualizadas e em containers no mesmo cluster do OpenShift.

[.big]#*Treinamentos recomendados*#

* Não há pré-requisitos para esta visão geral técnica

[.big]#*Requisitos técnicos*#

* N/D

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/do016-red-hat-openshift-virtualization-technical-overview
