// Este arquivo é mantido executando scripts/refresh-training.py script

= Containers, Kubernetes and Red Hat OpenShift Technical Overview (DO080)

*Uma introdução ao gerenciamento de aplicações em containers usando o Kubernetes e o Red Hat OpenShift*

[.big]#*Descrição do curso*#

O curso Containers, Kubernetes and Red Hat OpenShift Technical Overview (DO080) é uma série de vídeos online on demand que apresenta os containers Linux e a tecnologia de orquestração de containers usando o Kubernetes e o Red Hat OpenShift.

Este curso é baseado no Red Hat OpenShift Container Platform 4.12.

[.big]#*Resumo do conteúdo*#

* Descrição do que são containers e aplicações em containers.
* Introdução ao Kubernetes e ao OpenShift.
* Criação de um cluster do OpenShift.
* Interação com OpenShift usando a linha de comando e o console web.
* Gerenciamento de máquinas e nós com operadores do OpenShift.
* Implantação de aplicações com Helm e source-to-image.
* Controle de acesso ao OpenShift.

[.big]#*Público-alvo*#

Qualquer pessoa interessada em aprender sobre o valor da tecnologia de containers, a conteinerização de aplicações e a implantação delas em escala em um cluster do OpenShift.

[.big]#*Pré-requisitos*#

Não há pré-requisitos para este curso.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/do080-deploying-containerized-applications-technical-overview
