// Este arquivo é mantido executando scripts/refresh-training.py script

= Developing Cloud-Native Applications with Microservices Architectures (DO092)

[.big]#*Descrição do curso*#

*Identifique as estruturas e ferramentas ideias para criar sua arquitetura de microsserviços*

O curso Developing Cloud-Native Applications with Microservices Architectures (DO092) consiste em uma série de vídeos on-line e sob demanda que ensina como combinar estruturas e ferramentas diferentes para criar uma arquitetura de microsserviços que atenda às necessidades da sua empresa.

Fala-se muito sobre a arquitetura de microsserviços, mas a execução e compreensão dessa arquitetura pode ser um grande desafio. Este curso organizado em uma série de vídeos apresenta o conceito de microsserviços, analisa as várias estruturas e ambientes de execução de microsserviços e, por fim, demonstra as técnicas para implantá-los usando um pipeline de DevOps descomplicado. Serão abordados os tópicos de containers, Docker, Spring Boot, NodeJS, .NET, OpenShift, Jenkins, Vert.x, Kubernetes e muito mais.

*Obs:* você pode assistir a todos os vídeos ou apenas aos que forem de seu interesse. Não há laboratórios hands-on nem reconhecimento de conclusão associados a este curso.

[.big]#*Público do curso*#

Desenvolvedores Java™ e qualquer pessoa interessada em OpenShift e Kubernetes.

Compreensão sobre arquitetura de sistemas de TI e software.

[.big]#*Pré-requisitos do curso*#

* Compreensão sobre arquitetura de sistemas de TI e software.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/do092-developing-cloud-native-applications-microservices-architectures
