// Este arquivo é mantido executando scripts/refresh-training.py script

= Introduction to Microsoft Azure Red Hat OpenShift (DO121)

[.big]#*Descrição do curso*#

*Aprenda a implantar, acessar e realizar personalizações básicas em um cluster do Microsoft Azure Red Hat OpenShift.*

Com o DO121, os operadores de plataforma aprendem a provisionar clusters gerenciados usando o Microsoft Azure Red Hat OpenShift. O curso também ensina como fazer personalizações básicas de dia 2 nesses clusters para integrar aplicações e seus respectivos desenvolvedores.

Após a conclusão do curso, você receberá 45 dias de acesso prolongado aos laboratórios hands-on para qualquer curso que inclua um ambiente virtual.

*Observação*: este curso é individualizado. As durações podem variar de acordo com a entrega. Para conferir todos os detalhes, a programação e os preços do curso, selecione a localização e clique em "Registre-se" no menu à direita.

[.big]#*Resumo do conteúdo*#

* Conhecer o OpenShift gerenciado
* Identificar os pré-requisitos para criar um cluster do Microsoft Azure Red Hat OpenShift
* Acessar um cluster do Microsoft Azure Red Hat OpenShift como administrador e como usuário de self-service de desenvolvedores
* Conectar um cluster do Microsoft Azure Red Hat OpenShift ao Red Hat Services
* Configurar classes de armazenamento adicionais e o encaminhamento de logs para o Azure Monitor
* Criar pools de nós dedicados e configurar a escalabilidade automática de nós

[.big]#*Público-alvo*#

* Profissionais de operações de TI, como administradores de sistema, operadores de plataforma e engenheiros de nuvem.
* Profissionais de infraestrutura de aplicações e desenvolvimento, como engenheiros de DevOps e de confiabilidade de sites.

[.big]#*Treinamentos recomendados*#

* Todos os alunos precisam conhecer o Microsoft Azure, incluindo a operação e o gerenciamento dos recursos de computação, armazenamento e rede dessa plataforma.
* No caso dos alunos sem experiência no Red Hat OpenShift, o recomendado é aprender as habilidades básicas de gerenciamento de clusters do Red Hat OpenShift antes de realizar o curso DO121. Estes são os cursos exigidos:
** https://www.redhat.com/pt-br/services/training/red-hat-openshift-administration-i-operating-a-production-cluster[Red Hat OpenShift Administration I: Operating a Production Cluster (DO180)]
** https://www.redhat.com/pt-br/services/training/red-hat-openshift-administration-ii-configuring-a-production-cluster[Red Hat OpenShift Administration II: Operating a Production Kubernetes Cluster (DO280)]
* Recomendamos aos alunos com experiência no gerenciamento de clusters do Kubernetes que façam os cursos DO180 e DO280 antes do DO121 ou que aprendam pelo menos as habilidades básicas para operar os clusters do Red Hat OpenShift. Para isso, a Red Hat disponibiliza os seguintes recursos gratuitos:
** https://developers.redhat.com/developer-sandbox[Sandbox do Red Hat Developer para o OpenShift]
** https://developers.redhat.com/learn/openshift[Conhecimentos do Red Hat Developer sobre OpenShift e Kubernetes]
** https://www.redhat.com/pt-br/services/training/do080-deploying-containerized-applications-technical-overview[Containers, Kubernetes and Red Hat OpenShift Technical Overview (DO080)]

[.big]#*Requisitos técnicos*#

* A conexão com a Internet é necessária para acessar os serviços de computação em nuvem do Azure por meio do portal ou da interface de linha de comando (CLI) do Azure. Você também precisará acessar o Red Hat Hybrid Cloud Console e os serviços de computação em nuvem da Red Hat associados.
* Os alunos precisam ter uma conta ativa do Azure com um método de pagamento associado. Isso é necessário devido aos recursos do Azure que serão consumidos pelos clusters do Microsoft Azure Red Hat OpenShift.
* Os alunos precisam ter uma conta ativa no Portal do Cliente Red Hat ou uma inscrição gratuita no https://developers.redhat.com/about[programa Red Hat Developer.]

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/do121-introduction-microsoft-azure-red-hat-openshift
