// Este arquivo é mantido executando scripts/refresh-training.py script

= Red Hat OpenShift Administration I: Operating a Production Cluster (DO180)

*Implante, gerencie e solucione problemas de aplicações em containers executadas como cargas de trabalho do Kubernetes em clusters do OpenShift.*

[.big]#*Descrição do curso*#

O curso Red Hat OpenShift Administration I: Operating a Production Cluster (DO180) prepara administradores de cluster do OpenShift para o gerenciamento de cargas de trabalho do Kubernetes. Além disso, ensina a colaborar com desenvolvedores, engenheiros de DevOps, administradores de sistema e SREs para garantir a disponibilidade das cargas de trabalho de aplicações. O foco deste curso é o gerenciamento de aplicações típicas para usuários finais que, muitas vezes, estão acessíveis em uma interface de usuário web ou mobile e representam a maioria das cargas de trabalho nativas em nuvem e em containers. O gerenciamento de aplicações também inclui implantar e atualizar dependências, como bancos de dados, sistemas de mensageria e sistemas de autenticação.

As habilidades que você aprende neste curso se aplicam a todas as versões do OpenShift, incluindo o Red Hat OpenShift on AWS (ROSA), o Azure Red Hat OpenShift e o OpenShift Container Platform.

Este curso é baseado no Red Hat OpenShift 4.14.

Após a conclusão do curso, o acesso prático ao laboratório permanecerá disponível por até 45 dias para qualquer curso presencial que inclua um ambiente virtual.

*Observação*: este curso é oferecido como aulas virtuais em cinco dias ou em ritmo individualizado. A duração pode variar de acordo com a entrega. Para conferir todos os detalhes, a programação e os preços do curso, selecione a localização e clique em "Registre-se" no menu à direita.

[.big]#*Resumo do conteúdo do curso*#

* Gerenciamento de clusters do OpenShift usando a interface da linha de comando e o console web.
* Implantação de aplicações no OpenShift a partir de imagens de container, templates e manifestos do Kubernetes.
* Solução de problemas de conectividade de rede entre aplicações dentro e fora de um cluster do OpenShift.
* Conexão de cargas de trabalho do Kubernetes com o armazenamento dos dados das aplicações.
* Configuração de cargas de trabalho do Kubernetes para que tenham alta disponibilidade e confiabilidade.
* Gerenciamento de atualizações de imagens de container, configurações e manifestos do Kubernetes de uma aplicação.

[.big]#*Público-alvo*#

* Principal: engenheiros de plataforma, administradores de sistema, administradores de nuvem e outras funções de TI relacionadas à infraestrutura que são responsáveis pelo suporte de primeira camada da infraestrutura de aplicações e têm interesse em gerenciar clusters do OpenShift e aplicações em containers.
* Secundário: arquitetos empresariais, engenheiros de confiabilidade de sites, engenheiros de DevOps e outras funções de TI relacionadas a aplicações que são responsáveis por projetar a infraestrutura de aplicações.
* Desenvolvedores e engenheiros de confiabilidade de sites iniciantes na tecnologia de containers devem se inscrever no curso https://www.redhat.com/pt-br/services/training/do188-red-hat-open-shift-development-introduction-containers-with-podman[Red Hat OpenShift Development I: Introduction to Containers with Podman (DO188)].

[.big]#*Treinamentos recomendados*#

* https://skills.ole.redhat.com/[Faça nossa avaliação gratuita] para saber se esta é a melhor opção para as suas habilidades.
* Pré-requisitos: ter concluído o curso https://www.redhat.com/pt-br/services/training/do080-deploying-containerized-applications-technical-overview[Containers, Kubernetes and Red Hat OpenShift Technical Overview (DO080)] ou ter conhecimento equivalente em containers Linux.
* Pré-requisitos: ter concluído o curso https://www.redhat.com/pt-br/services/training/getting-started-with-linux-fundamentals[Getting Started with Linux Fundamentals (RH104)] ou ter proficiência equivalente no uso de uma interface de linha de comando, idealmente operando um shell bash.

[.big]#*Requisitos técnicos*#

* Para aprendizado virtual, em ritmo próprio, ou treinamento presencial:
** É necessário ter acesso à internet.
** Os laboratórios são realizados no ambiente de aprendizado online da Red Hat.
** Para treinamento presencial, a Red Hat fornecerá um ambiente de curso instalado localmente como alternativa no futuro.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/red-hat-openshift-administration-i-operating-a-production-cluster
