// Este arquivo é mantido executando scripts/refresh-training.py script

= Cloud-native API Administration with Red Hat 3scale API Management (DO240)

[.big]#*Descrição do curso*#

*Gerencie, monetize e proteja APIs com o Red Hat 3scale API Management*

O Build and Administer APIs with Red Hat 3scale API Management (DO240) é um curso hands-on e baseado em laboratório destinado a SREs e administradores que oferece uma introdução ao gerenciamento de APIs nativas em nuvem usando o Red Hat® 3scale API Management. Este curso permite que desenvolvedores e administradores instalem, administrem, monetizem, protejam e documentem suas APIs nativas em nuvem.

Este curso é baseado no Red Hat 3scale API Management 2.11.

Após a conclusão do curso, o acesso prático ao laboratório permanecerá disponível por até 45 dias para qualquer curso presencial que inclua um ambiente virtual.

*Observação:* este curso é individualizado. A duração pode variar de acordo com a entrega. Para conferir todos os detalhes, a programação e os preços do curso, selecione a localização e clique em "Registre-se" no menu à direita.

[.big]#*Resumo do conteúdo*#

* Entenda a arquitetura e as principais funcionalidades do 3scale API Management.
* Aprenda os casos e estratégias de uso de API mais comuns.
* Instale o 3scale API Management no OpenShift.
* Estabeleça e configure planos de subscrição e limites de taxa.
* Configure e personalize o gateway de API usando políticas.
* Monitore e analise o tráfego da API.
* Configure e teste a descoberta de serviços de API.
* Configure um portal do desenvolvedor e monetize suas APIs.
* Configure a segurança da API usando tokens, pares de chaves de API e OAuth/OIDC usando o Red Hat Single Sign-on (SSO).

[.big]#*Público-alvo*#

* Engenheiros de confiabilidade de sites e administradores do OpenShift interessados em usar o 3scale API Management para gerenciar, monitorar, proteger e monetizar suas APIs nativas em nuvem.

[.big]#*Pré-requisitos do curso*#

* https://skills.ole.redhat.com/[Faça nossa avaliação gratuita] e descubra se esta é a melhor opção para você.
* Ter concluído o https://www.redhat.com/pt-br/services/training/red-hat-openshift-administration-ii-configuring-a-production-cluster[Red Hat OpenShift Administration II: Operating a Production Kubernetes Cluster (DO280)] ou demonstrrar conhecimento equivalente.
* Ter familiaridade com APIs REST de teste e conceitos de segurança, como chaves de API, tokens e OAuth/OIDC.

[.big]#*Requisitos técnicos*#

* Para aprendizado virtual, em ritmo próprio, ou treinamento presencial:
** É necessário ter acesso à internet.
** Os laboratórios são realizados no ambiente de aprendizado online da Red Hat.
** Para treinamento presencial, a Red Hat fornecerá um ambiente de curso instalado localmente como alternativa no futuro.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/do240-build-and-administer-apis-red-hat-3scale-api-management
