// Este arquivo é mantido executando scripts/refresh-training.py script

= Red Hat OpenShift Developer II: Building and Deploying Cloud-native Applications (DO288)

[.big]#*Descrição do curso*#

*Projeto, criação e implantação de aplicações conteinerizadas no Red Hat OpenShift.*

Com o curso Red Hat OpenShift Developer II: Building and Deploying Cloud-native Applications (DO288), você aprende a projetar, criar e implantar aplicações de software em containers em um cluster do OpenShift.

Seja para a migração de aplicações existentes ou a criação de aplicações nativas em container, você aprenderá a aumentar a produtividade dos desenvolvedores com base no Red Hat® OpenShift. Essa solução é uma plataforma de aplicações em containers que permite às empresas gerenciar implantações de container e escalar as respectivas aplicações com o Kubernetes.

As habilidades que você aprende neste curso podem ser aplicadas usando todas as versões do Red Hat OpenShift, incluindo o Red Hat OpenShift on AWS (ROSA), o Azure Red Hat OpenShift (ARO) e o Red Hat OpenShift Container Platform.

Este curso é baseado no Red Hat OpenShift 4.18.

Após a conclusão do curso, você terá 45 dias de acesso prolongado aos laboratórios hands-on de qualquer curso que inclua um ambiente virtual.

*Observação*: este curso é oferecido como aulas virtuais em quatro dias ou em ritmo individualizado. A duração pode variar de acordo com a entrega. Para conferir todos os detalhes, a programação e os preços do curso, selecione a localização e clique em "Registre-se" no menu à direita.

[.big]#*Resumo do conteúdo*#

* Funcionalidades para desenvolvedores no console web do Red Hat OpenShift
* Criação e publicação de imagens de container para o Red Hat OpenShift
* Gerenciamento de implantações de containers no Red Hat OpenShift
* Criação e implantação aplicações em vários containers no Red Hat OpenShift
* Implantação de aplicações em vários containers usando gráficos Helm e Kustomize
* Criação de verificações de integridade para monitorar e aumentar a confiabilidade da aplicação
* Criação de fluxos de trabalho de CI/CD usando o Red Hat OpenShift Pipelines

[.big]#*Público do curso*#

* Desenvolvedores de software
* Arquitetos de software

[.big]#*Recomendações para o curso*#

* https://skills.ole.redhat.com/[Faça nossa avaliação gratuita] para saber se esta é a melhor opção para as suas habilidades.
* Concluir o curso https://www.redhat.com/pt-br/services/training/do188-red-hat-open-shift-development-introduction-containers-with-podman[Red Hat OpenShift Development I: Introduction to Containers with Podman (DO188)] ou ter experiência equivalente.
* Ter certificação RHCSA ou superior é útil para navegação e uso da linha de comando, mas não é obrigatório.

[.big]#*Requisitos técnicos*#

* Para aprendizado virtual, em ritmo próprio, ou treinamento presencial:
** É necessário ter acesso à internet.
** Os laboratórios são realizados no ambiente de aprendizado online da Red Hat.
** Para treinamento presencial, a Red Hat fornecerá um ambiente de curso instalado localmente como alternativa no futuro.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/red-hat-openshift-developer-ii-building-and-deploying-cloud-native-applications
