// Este arquivo é mantido executando scripts/refresh-training.py script

= Red Hat OpenShift Administration II: Configuring a Production Cluster (DO280)

[.big]#*Descrição do curso*#

*Configure e gerencie clusters do OpenShift para manter a segurança e a confiabilidade em várias aplicações e equipes de desenvolvimento.*

O Red Hat OpenShift Administration II: Configuring a Production Cluster (DO280) prepara os administradores de cluster do OpenShift para realizar tarefas administrativas diárias em clusters que hospedam aplicações fornecidas por equipes internas e fornecedores externos, habilitar o self-service para usuários do cluster com diferentes funções e implantar aplicações que exigem permissões especiais, como ferramentas de CI/CD, monitoramento de desempenho e verificações de segurança. O foco deste curso é a configuração de funcionalidades de multitenancy e segurança do OpenShift e o gerenciamento de módulos complementares baseados em operadores.

As habilidades que você aprende neste curso podem ser aplicadas em todas as versões do OpenShift, incluindo o Red Hat OpenShift on AWS (ROSA), o Azure Red Hat OpenShift e o OpenShift Container Platform.

Este curso é baseado no OpenShift Container Platform 4.14.

Após a conclusão do curso, o acesso prático ao laboratório permanecerá disponível por até 45 dias para qualquer curso presencial que inclua um ambiente virtual.

*Observação:*

Este curso é oferecido nos seguintes formatos: presencial (quatro dias), aula virtual (cinco dias) ou online (individualizado).A duração pode variar de acordo com a entrega. Para conferir todos os detalhes, a programação e os preços do curso, selecione a localização e clique em "Registre-se" no menu à direita.

[.big]#*Tópicos do curso*#

* Implantação de aplicações em pacotes usando manifestos, templates, kustomize e helm.
* Configuração de autenticação e autorização de usuários e aplicações.
* Proteção do tráfego de rede com políticas de rede e exposição de aplicações com acesso à rede adequado.
* Implantação e gerenciamento de aplicações usando manifestos de recursos.
* Habilitação de self-service para desenvolvedores de projetos de aplicações.
* Gerenciamento de atualizações do cluster do OpenShift e de operadores do Kubernetes.

[.big]#*Público-alvo*#

* Administradores de plataforma, administradores de sistema, administradores de nuvem e outras funções de TI relativas a infraestrutura que são responsáveis por gerenciar e manter infraestrutura para aplicações
* Arquitetos empresariais, engenheiros de confiabilidade de sites, engenheiros de DevOps e outras funções de TI relacionadas a aplicações que são responsáveis por projetar a infraestrutura de aplicações.

[.big]#*Treinamentos recomendados*#

* https://skills.ole.redhat.com/[Faça nossa avaliação gratuita] para saber se esta é a melhor opção para suas habilidades.
* Prerrequisitos: https://www.redhat.com/pt-br/services/training/red-hat-openshift-administration-i-operating-a-production-cluster[Red Hat OpenShift Administration I: Operating a Production Cluster (DO180v4.14)] ou habilidades equivalentes em implantar e gerenciar aplicações do Kubernetes usando o console web do OpenShift e interfaces de linha de comando.
* Não é necessário ter experiência significativa com o Linux System Administration para este curso. Habilidades básicas em operação de um shell Bash, manipulação de arquivos e processos e verificação de confirmações do sistema, como endereços de rede, são necessárias e suficientes. Encorajamos os alunos a fazer o curso https://www.redhat.com/pt-br/services/training/getting-started-with-linux-fundamentals[Getting Started with Linux Fundamentals (RH104)] antes de se inscreverem no DO280.

[.big]#*Requisitos técnicos*#

* Para aprendizado virtual, em ritmo próprio, ou treinamento presencial:
** É necessário ter acesso à internet.
** Os laboratórios são realizados no ambiente de aprendizado online da Red Hat.
** Para treinamento presencial, a Red Hat fornecerá um ambiente de curso instalado localmente como alternativa no futuro.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/red-hat-openshift-administration-ii-configuring-a-production-cluster
