// Este arquivo é mantido executando scripts/refresh-training.py script

= Red Hat DevOps Pipelines and Processes: CI/CD with Jenkins, Git, and Test Driven Development (DO400)

[.big]#*Descrição do curso*#

*Desenvolva habilidades essenciais para implementar processos e fluxos de trabalho com desenvolvimento ágil e DevOps.*

As práticas de DevOps abriram espaço para a transformação digital das empresas que puderam migrar da abordagem monolítica em cascata para um processo ágil de implantação rápida baseado na nuvem. Essa transformação exige uma equipe de desenvolvedores treinados para usar ferramentas que os permitem passar mais tempo programando e testando, e menos tempo solucionando problemas. O Red Hat DevOps Pipelines and Processes: CI/CD with Jenkins, Git, and Test-Driven Development (TDD) é uma introdução prática ao DevOps para desenvolvedores que ensina as habilidades e tecnologias necessárias para a criação e implantação automatizadas de aplicações nativas em nuvem.

Após a conclusão do curso, o acesso prático ao laboratório permanecerá disponível por até 45 dias para qualquer curso presencial que inclua um ambiente virtual.

*Observação*: este curso é individualizado. A duração pode variar de acordo com a entrega. Para conferir todos os detalhes, a programação e os preços do curso, selecione a localização e clique em "Registre-se" no menu à direita.

[.big]#*Resumo do conteúdo do curso*#

* Controle de versão com o Git.
* Criação e execução de pipelines no Jenkins.
* Estratégias de lançamento.
* Criação de aplicações com desenvolvimento orientado por testes.
* Verificação da segurança e análise do código das aplicações.
* Monitoramento de aplicações e pipelines.
* Consumo e solução de problemas em pipelines.

[.big]#*Público-alvo*#

Este curso foi elaborado para desenvolvedores de aplicações.

[.big]#*Treinamentos recomendados*#

É necessária experiência com desenvolvimento de aplicações em Java, Node.js, Python ou outros.



Embora não seja obrigatório, é recomendável ter experiência com desenvolvimento de aplicações ou a concluir o curso https://www.redhat.com/pt-br/services/training/ad183-red-hat-application-development-i-programming-java-ee[Red Hat Application Development I: Programming in Java EE (AD183).]



Proficiência no uso de IDEs, como Red Hat® Developer Studio ou VSCode.



Não é exigida, mas recomenda-se a certificação https://www.redhat.com/pt-br/services/training/do101-introduction-openshift-applications[Introduction to OpenShift Applications (DO101)]



https://rhtapps.redhat.com/assessment/[Faça nossa avaliação gratuita] para saber se esta é a melhor opção para as suas habilidades.



[.big]#*Requisitos técnicos*#

* Para aprendizado virtual, em ritmo próprio, ou treinamento presencial:
** É necessário ter acesso à internet.
** Os laboratórios são realizados no ambiente de aprendizado online da Red Hat.
** Para treinamento presencial, a Red Hat fornecerá um ambiente de curso instalado localmente como alternativa no futuro.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/do400-red-hat-devops-pipelines-and-processes-with-jenkins-git-and-test-driven-development
