// Este arquivo é mantido executando scripts/refresh-training.py script

= Securing Kubernetes Clusters with Red Hat Advanced Cluster Security (DO430)

[.big]#*Descrição do curso*#

*Supere os desafios de segurança aplicando o Red Hat Advanced Cluster Security for Kubernetes em um ambiente de cluster do OpenShift.*

Os clientes querem saber como o Red Hat Advanced Cluster Security for Kubernetes (RHACS) pode ajudar a superar os desafios de segurança. No entanto, é provável que eles tenham equipes de segurança sem experiência em Kubernetes e OpenShift, o que dificulta a implementação. Em específico, as equipes de segurança têm várias necessidades:

* Integrar práticas de DevOps ao RHACS e aprender a usar a solução para automatizar o DevSecOps com o objetivo de operacionalizar e proteger a cadeia de suprimentos, a infraestrutura e as cargas de trabalho
* Avaliar a conformidade com base nos padrões do setor e receber orientações sobre correção
* Implementar o gerenciamento de vulnerabilidades, aplicar políticas e segmentar a rede para proteger as cargas de trabalho

É provável que os clientes do RHACS já estejam usando registros de imagem externos e ferramentas de Gerenciamento de eventos e informações de segurança (SIEM). Eles precisam integrar componentes externos existentes ao RHACS para atingir as metas de segurança.

Após a conclusão do curso, você receberá acesso estendido de 45 dias aos laboratórios práticos para todos os cursos que incluem um ambiente virtual.

*Observação:* este curso pode ser concluído em três dias no modelo presencial, em quatro dias no modelo virtual ou no ritmo que você preferir. A duração pode variar com base no formato escolhido. Para conferir todos os detalhes, a programação e os preços do curso, selecione sua localização e clique em "Enviar" no menu à direita.

[.big]#*Resumo do conteúdo do curso*#

* Conhecer e implementar a arquitetura do RHACS e os componentes dela, seguir as práticas recomendadas de instalação e solucionar problemas comuns nesse processo
* Interpretar os resultados das verificações de vulnerabilidades, gerar relatórios e avaliar os riscos para priorizar as ações de segurança
* Implementar e fiscalizar políticas do RHACS em todos os estágios da aplicação de políticas para proteger o pipeline de CI/CD e a cadeia de suprimentos de software
* Identificar e corrigir as falhas de segurança nas políticas de rede usando o Gráfico de rede e aplicar as políticas geradas em um pipeline de CI/CD
* Executar verificações de conformidade integradas, além de instalar e executar um operador para determinar a conformidade do cluster com as políticas e padrões de segurança e produzir relatórios e evidências
* Integrar componentes externos ao RHACS para disponibilizar mais funções, que incluem notificações centralizadas, backup, restauração e gerenciamento de identidades e permissões

[.big]#*Público-alvo*#

* Profissionais de segurança responsáveis por identificar, analisar e mitigar ameaças nos ambientes do Kubernetes
* Administradores de infraestrutura que gerenciam e protegem clusters Kubernetes, além de assegurar a robustez e a conformidade da infraestrutura com os padrões de segurança
* Engenheiros de plataforma que seguem práticas de DevOps e DevSecOps, integrando a proteção ao pipeline de CI/CD para possibilitar a implantação segura e o monitoramento contínuo das aplicações em container

[.big]#*Pré-requisitos do curso*#

* https://skills.ole.redhat.com/en[Faça nossa avaliação gratuita] para saber se esta é a melhor opção para suas habilidades
* https://www.redhat.com/pt-br/services/training/red-hat-openshift-administration-ii-configuring-a-production-cluster[Red Hat OpenShift Administration II: Configuring a Production Cluster | DO280]

[.big]#*Requisitos técnicos*#

* Para aprendizado virtual, em ritmo próprio, ou treinamento presencial:
** É necessário ter acesso à internet.
** Os laboratórios são realizados no ambiente de aprendizado online da Red Hat.
** Para treinamento presencial, a Red Hat fornecerá um ambiente de curso instalado localmente como alternativa no futuro.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/do430-securing-kubernetes-clusters-red-hat-advanced-cluster-security
