// Este arquivo é mantido executando scripts/refresh-training.py script

= Container Adoption Boot Camp (DO700)

[.big]#*Descrição do curso*#

*Suporte à infraestrutura para adoção de aplicações nativas em containers, Kubernetes e práticas de DevOps*

O treinamento Container Adoption Boot Camp for Administrators (DO700) é uma experiência imersiva, intensiva e hands-on em gerenciamento em escala empresarial de aplicações nativas em containers implantadas na versão do Kubernetes da Red Hat, o Red Hat® OpenShift® Container Platform. Este curso é destinado aos profissionais que querem avançar significativamente na jornada da transformação digital. Mas para fazer essa mudança, você precisa oferecer suporte a um número cada vez maior de clusters, stakeholders, aplicações e usuários para viabilizar implantações em grande escala. As habilidades adquiridas neste curso podem ser aplicadas a edições autogerenciadas do OpenShift e a edições de serviços gerenciados, como o Red Hat OpenShift on AWS (ROSA) e o Azure Red Hat OpenShift. Como parte da inscrição, você receberá um ano dohttps://www.redhat.com/pt-br/services/training/learning-subscription[Red Hat Learning Subscription Standard], que dá a você acesso ilimitado a todos os nossos cursos online. Além disso, você pode fazer até cinco exames únicos e refazer qualquer um desses exames caso não seja aprovado.

Essa coleção de cursos é baseada no Red Hat OpenShift Container Platform 4.14.

*Observação:* este curso é oferecido como aulas virtuais de dez dias. A duração pode variar de acordo com a entrega. Para conferir todos os detalhes, a programação e os preços do curso, selecione a localização e clique em "Registre-se" no menu à direita.

[.big]#*De 5 a 10 tópicos*#

* Introdução ao Kubernetes e ao Red Hat OpenShift
* Implantação e solução de problemas de aplicações em containers no OpenShift
* Controle do acesso a projetos com base em funções usando controle de acesso baseado em função (RBAC)
* Configuração do gerenciamento de identidade e autenticação do OpenShift
* Isolamento de aplicações com políticas de rede
* Controle do uso de recursos com cotas e limites
* Automação das tarefas administrativas do OpenShift usando o operador OpenShift GitOps
* Implantação de aplicações em pacotes com templates do OpenShift e gráficos Helm
* Provisionamento de armazenamento persistente sob medida para os requisitos de aplicações
* Backup e restauração aplicações em containers com a API do OpenShift para proteção de dados (OADP)

[.big]#*Público-alvo*#

* Administradores de sistemas, administradores de nuvem e engenheiros de confiabilidade de sites (SREs) interessados em adotar tecnologias de container e Kubernetes.

[.big]#*Treinamentos recomendados*#

* Ter a certificação https://www.redhat.com/pt-br/services/certification/rhcsa[Red Hat Certified System Administrator (RHCSA)] ou demonstrar experiência equivalente

[.big]#*Requisitos técnicos*#

* É necessário ter conexão com a Internet durante o curso para acessar os clusters dedicados e compartilhados do OpenShift.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/do700-container-adoption-boot-camp
