// Este arquivo é mantido executando scripts/refresh-training.py script

= Red Hat Ansible Automation Platform Boot Camp (DO710)

[.big]#*Descrição do curso*#

*Aprenda a automatizar as tarefas de administração de sistemas Linux com o Red Hat Ansible Automation Platform, além de gerenciar fluxos de trabalho de automação complexos em escala e evitar pontos únicos de falha.*

* O curso Ansible Automation Platform Boot Camp (DO710) foi elaborado para desenvolvedores e administradores de Linux que precisam automatizar as etapas repetíveis e suscetíveis a erros de provisionamento e configuração de sistemas e de implantação e orquestração de aplicações. Aprenda práticas recomendadas para o desenvolvimento da automação usando código reutilizável, técnicas avançadas de playbook, ambientes de execução compartilhados e preparação de automação escalável com o automation content navigator. Implante o automation controller para gerenciar fluxos de trabalho de automação de maneira centralizada, o automation mesh para expandir e distribuir a capacidade de execução e o automation hub privado para gerenciar coleções do Ansible Content Collections e automation execution environments usados por desenvolvedores de automação.
* Esta coleção de cursos é baseada no Red Hat Ansible Automation Platform 2.2.
* Como parte da inscrição, você receberá o Red Hat Learning Subscription Standard por um ano, que dá acesso ilimitado a todos os nossos cursos online, além de até cinco exames de certificação.

*Observação:* este curso é oferecido como aulas virtuais de dez dias. As durações podem variar de acordo com a entrega. Para conferir todos os detalhes, a programação e os preços do curso, selecione a localização e clique em "Registre-se" no menu à direita.

[.big]#*Resumo do conteúdo do curso*#

* Instalar o Red Hat Ansible Automation Platform em nós de controle.
* Criar e atualizar inventários de hosts gerenciados e gerenciar as conexões deles.
* Automatizar tarefas administrativas com playbooks do Ansible.
* Criar playbooks eficazes em escala.
* Proteger dados confidenciais usados pelo Ansible Automation Platform com o Ansible Vault.
* Reutilizar o código e simplificar o desenvolvimento de playbooks com Ansible Roles e Ansible Content Collections.
* Aplicar as práticas recomendadas para automatizar de modo eficaz e eficiente com o Ansible.
* Fazer operações de automação como atualizações contínuas.
* Usar funcionalidades avançadas do Red Hat Ansible Automation Platform, incluindo filtros e plug-ins, para trabalhar com dados.
* Criar automation execution environments para conter e ajustar a escala do Red Hat Ansible Automation.
* Potencializar os recursos do automation content navigator para desenvolver playbooks do Ansible.
* Discutir a arquitetura do Red Hat Ansible Automation Platform 2.
* Instalar e configurar automation controllers e automation hubs privados para coordenar e escalar de forma centralizada o Red Hat Ansible Automation.
* Integrar o Red Hat Ansible Automation Platform com serviços de repositório Git centralizados, como o GitLab.
* Gerenciar usuários, equipes e permissões de acesso nos serviços do Red Hat Ansible Automation Platform.
* Criar e gerenciar fluxos de trabalho que executam a automação com base no sucesso ou falha de tarefas anteriores.
* Solucionar problemas e fazer a manutenção dos serviços do Red Hat Ansible Automation Platform.
* Discutir as práticas recomendadas para garantir alta disponibilidade e escalabilidade de um grande cluster de automação.

[.big]#*Público-alvo*#

Este curso é destinado a administradores de sistemas Linux, engenheiros de DevOps, de confiabilidade de sites e de automação de infraestruturas e desenvolvedores responsáveis por tarefas repetíveis, como:

* Automatizar o gerenciamento de configurações
* Garantir a implantação consistente e repetível de aplicações
* Provisionar e implantar servidores de desenvolvimento, teste e produção
* Integrar fluxos de trabalho de entrega/integração contínuas de DevOps

[.big]#*Treinamentos recomendados*#

* Ter a certificação Red Hat Certified System Administrator (RHCSA) ou demonstrar experiência equivalente

[.big]#*Considerações técnicas*#

* Este curso não exige requisitos técnicos especiais ao participante.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/do710-ansible-automation-platform-bootcamp
