// Este arquivo é mantido executando scripts/refresh-training.py script

= Developing Rules Applications with Red Hat Decision Manager (JB463)

[.big]#*Descrição do curso*#

*Aprenda a criar, testar, fazer o debug e controlar regras de negócios em um ambiente de produção*

O Developing Rules Applications with Red Hat Decision Manager (JB463) ensina aos desenvolvedores de regras e aos desenvolvedores de aplicações corporativos Java™ como criar, testar, fazer o debug e controlar as regras de negócios, gerar pacotes de regras e como o ambiente de execução do Red Hat Decision Manager executa as regras.

Os alunos usarão o Red Hat Developer Studio 7 e o Red Hat Decision Manager 6 para realizar tarefas hands-on detalhadas que possibilitam a criação e o gerenciamento de regras de negócios em um ambiente de produção. Os princípios ensinados nesse curso podem ser aplicados na implementação de uma solução autônoma do Red Hat JBoss BRMS ou da solução Red Hat JBoss BPM Suite (gerenciamento de processos de negócios).

[.big]#*Resumo do conteúdo*#

* Criação de regras de negócios básicas no Red Hat Developer Studio.
* Criação de regras avançadas
* Teste e depuração de regras de negócios
* Uso de tabelas de decisão em uma planilha
* Criação e uso dos arquivos de mapeamento DSL
* Execução da regra de tempo de execução e arquitetura do Red Hat JBoss BRMS
* Controle de execução de regras e prevenção de conflitos
* Processamento de eventos complexos (CEP)

[.big]#*Público do curso*#

* Autores de regras responsáveis por criar e testar as regras usando o Red Hat Developer Studio
* Desenvolvedores de aplicativos Java responsáveis por desenvolver e integrar regras de negócios a aplicativos corporativos Java e Java JEE.

[.big]#*Pré-requisitos do curso*#

* Experiência básica em programação em Java e Java EE
* Conhecimento do Eclipse IDE, Maven e GIT é útil, mas não essencial
* Não é exigida experiência em desenvolvimento de regras de negócios

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/jb463-developing-rules-applications-red-hat-jboss-brms
