// Este arquivo é mantido executando scripts/refresh-training.py script

= Virtualization and Infrastructure Migration Technical Overview (RH018)

[.big]#*Descrição do curso*#

*Aprenda os fundamentos da virtualização open source e como planejar a migração*

O curso Virtualization and Infrastructure Migration Technical Overview (RH018) ajudará você a descobrir as vantagens da virtualização open source, como gerenciar melhor seus ativos de virtualização e a melhor maneira de migrar cargas de trabalho tradicionais de uma infraestrutura de virtualização proprietária para uma estrutura open source.

[.big]#*Resumo do curso*#

Por meio de vídeos on-line, sob demanda, você aprenderá a:

* Definir mapeamento da infraestrutura de forma simples. 
* Criar planos de migração para equilibrar as cargas de trabalho com confiança. 
* Criar planos de migração para reduzir as despesas em virtualização. 

[.big]#*Público do curso*#

* Arquitetos de TI
* Engenheiros de sistemas
* Operações de TI 

[.big]#*Pré-requisitos do curso*#

* Conhecimento básico em virtualização
* Habilidades básicas em administração de sistemas

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/rh018-virtualization-and-infrastructure-migration-technical-overview
