// Este arquivo é mantido executando scripts/refresh-training.py script

= Running Containers with Red Hat Technical Overview (RH065)

[.big]#*Descrição do curso*#

*Uma introdução básica ao gerenciamento de containers no Red Hat Enterprise Linux*

Os containers Linux são uma tecnologia cada vez mais importante que permite implantar aplicações com todo o ambiente de execução e movê-las facilmente entre diferentes ambientes operacionais (desenvolvimento, teste e produção) de maneira escalável e confiável.  Eles oferecem à sua equipe ferramentas que podem ser usadas para ajudar a implementar práticas de DevOps e integração e implantação contínuas (CI/CD), além de outros elementos de uma abordagem de aplicações nativas em nuvem.  O Running Containers with Red Hat Technical Overview (RH065) oferece uma introdução ao gerenciamento de containers do Red Hat Enterprise Linux. Os alunos aprenderão o que são containers e como usá-los para implantar aplicações de software em um servidor do Red Hat Enterprise Linux.

[.big]#*Resumo do conteúdo*#

* Obtenha, execute e gerencie serviços lightweight e simples como containers em um servidor do Red Hat Enterprise Linux.
* Explique o que é um container e como usá-lo para gerenciar e implantar aplicações com as respectivas dependências e bibliotecas de software de suporte.
* Instale ferramentas de gerenciamento de containers e execute um container simples sem raiz.
* Encontre, recupere, inspecione e gerencie imagens de container obtidas de um registro de containers remoto e armazenadas no seu servidor.
* Execute containers com opções avançadas, liste quais estão em execução no sistema e inicie, interrompa e elimine containers.
* Forneça armazenamento persistente para dados de containers montando um diretório a partir do host dentro de um container em execução.
* Inicie, interrompa e verifique o status de um container como um serviço do sistema.

[.big]#*Público-alvo*#

* Esse curso se destina a alunos interessados em uma introdução ao gerenciamento de containers no Red Hat Enterprise Linux.
* Alunos com habilidades básicas no Red Hat Enterprise Linux

[.big]#*Treinamentos recomendados*#

* Habilidades básicas com o Red Hat Enterprise Linux ou a https://www.redhat.com/pt-br/services/certification/rhcsa-991[certificação Red Hat Certified System Administrator (RHCSA)]
* https://www.redhat.com/pt-br/node/212491[Red Hat OpenShift I: Containers & Kubernetes (DO180)]

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/rh065-running-containers-red-hat-technical-overview
