// Este arquivo é mantido executando scripts/refresh-training.py script

= Curso Red Hat Certified System Administrator Rapid Track (RH199)

[.big]#*Descrição do curso*#

*Aprenda o básico sobre a configuração, administração e manutenção do Red Hat Enterprise Linux em um formato resumido feito para administradores de sistema Linux.*

O RHCSA Rapid Track course (RH199) inclui o Red Hat® Enterprise Linux® 10 e destina-se a alunos que já têm experiência significativa com a administração do Linux. Esse curso acelerado combina o conteúdo essencial dos cursos https://www.redhat.com/pt-br/services/training/rh124-red-hat-system-administration-i[Red Hat System Administration I (RH124)] e https://www.redhat.com/pt-br/services/training/rh134-red-hat-system-administration-ii[Red Hat System Administration II (RH134)] para ajudar os alunos a operarem, gerenciarem e manterem um sistema Red Hat Enterprise Linux.

Este curso é baseado no Red Hat Enterprise Linux 10.

[.big]#*Resumo do conteúdo do curso*#

* Gerenciamento de usuários, grupos e autenticação
* Gerenciamento de pacotes com uma nova estrutura de repositório e módulos do AppStream
* Uso e gerenciamento de software de desktop com o Flatpak
* Gerenciamento de processos, agendamento e ajustes
* Configuração de segurança e serviços de rede
* Criação de dispositivos de armazenamento, volumes e sistemas de arquivos, como gerenciamento de armazenamento Stratis
* Execução do gerenciamento do servidor com o utilitário da web Cockpit
* Solução de problemas e suporte

[.big]#*Público-alvo do curso*#

* Administradores de sistema, engenheiros de plataforma, desenvolvedores e outros profissionais de TI que tenham entendimento básico da linha de comando do Linux e queiram aprender as principais tarefas para administrar um sistema Red Hat Enterprise Linux.

[.big]#*Pré-requisitos do curso*#

* Familiaridade com conceitos fundamentais de computação do Linux, experiência como usuário do Linux e prontidão para realizar tarefas de administração de sistemas.
* É recomendável ter experiência de campo significativa como administrador de sistemas Linux.
* Se você não tiver experiência nos conceitos fundamentais de computação do Linux, a Red Hat recomenda começar pelo curso Red Hat System Administration I (RH124).
* https://www.redhat.com/rhtapps/assessment/[Faça nossa avaliação gratuita] para saber se esta é a melhor opção para suas habilidades.

[.big]#*Requisitos técnicos*#

* Para aulas online, presenciais e no ritmo que você preferir:
** É necessário ter acesso à internet.
** As aulas no laboratório são realizadas no Red Hat Online Learning.
** No caso das aulas presenciais, pode ser que no futuro a Red Hat disponibilize um ambiente local como alternativa.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/rh199-red-hat-certified-system-administrator-rapid-track-course
