// Este arquivo é mantido executando scripts/refresh-training.py script

= New Features in Red Hat Enterprise Linux (RH304)

[.big]#*Descrição do curso*#

*Conheça as novas funcionalidades e mudanças do Red Hat Enterprise Linux 10 para se preparar para a implantação.*

_"New Features in Red Hat Enterprise Linux"_ prepara os alunos para implantar e explorar as novas funcionalidades e melhorias do Red Hat Enterprise Linux 10 com sucesso. Este curso permite que os alunos identifiquem as principais diferenças e melhorias e aproveitem todo o potencial do RHEL 10. Os tópicos incluem otimização de desempenho, melhorias na segurança e alterações na interface de usuário. Este curso capacita os alunos para implementar o sistema de maneira eficaz e maximizar seus recursos no ambiente.

Após a conclusão do curso, você terá acesso estendido de 45 dias aos laboratórios práticos para todos os cursos que incluem um ambiente virtual.

*Observação:* este curso é oferecido nos formatos presencial (2 dias), aula virtual (3 dias) ou online (individualizado). A duração do curso pode variar de acordo com o formato escolhido. Para conferir todos os detalhes do curso, como programação e valores, selecione seu país e clique no botão "Enviar" à direita

[.big]#*Resumo do conteúdo do curso*#

* Descreva melhorias selecionadas e alterações nas funcionalidades do Red Hat Enterprise Linux 10.
* Instale o RHEL 10 de forma interativa, com o package mode ou use o Kickstart.
* Receba orientações e sugestões geradas por IA para gerenciar com eficiência um servidor RHEL usando o Red Hat Enterprise Linux Lightspeed.
* Use o Flatpak para instalar, atualizar e usar a aplicação de desktop do Red Hat Ecosystem Catalog.
* Gerencie containers e imagens de containers com as ferramentas de gerenciamento atualizadas.
* Crie, use, instale e atualize containers e servidores que usam gerenciamento de instalação baseado em imagem. 

[.big]#*Público-alvo*#

* Administradores de sistemas, engenheiros de plataforma, desenvolvedores e outros profissionais de TI com experiência no gerenciamento do Red Hat Enterprise Linux 9 ou versões anteriores, que precisem se preparar para a implantação e as operações do Red Hat Enterprise Linux 10.

[.big]#*Pré-requisitos do curso*#

* https://skills.ole.redhat.com/en[Faça nossa avaliação gratuita] para saber se esta é a melhor opção para as suas habilidades.
* https://www.redhat.com/pt-br/services/training/rh124-red-hat-system-administration-i[Red Hat System Administration I (RH124)] – Versão 9.3 ou ter experiência equivalente
* https://www.redhat.com/pt-br/services/training/rh134-red-hat-system-administration-ii[Red Hat System Administration II (RH134)] – Versão 9.3 ou ter experiência equivalente

[.big]#*Requisitos técnicos*#

* Para aprendizado virtual, em ritmo próprio, ou treinamento presencial:
** É necessário ter acesso à internet.
** Os laboratórios são realizados no ambiente de aprendizado online da Red Hat.
** Para treinamento presencial, a Red Hat fornecerá um ambiente de curso instalado localmente como alternativa no futuro.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/rh304-new-features-red-hat-enterprise-linux
