// Este arquivo é mantido executando scripts/refresh-training.py script

= Red Hat Enterprise Linux Diagnostics and Troubleshooting (RH342)

[.big]#*Descrição do curso*#

*Diagnostique problemas, colete informações e solucione problemas comuns com o Red Hat Enterprise Linux*

O curso Red Hat Enterprise Linux Diagnostics and Troubleshooting (RH342) fornece a administradores de sistemas as ferramentas e as técnicas necessárias para diagnosticar e corrigir com êxito uma variedade de possíveis problemas. Os alunos trabalharão em problemas hands-on comuns em vários subsistemas para diagnosticá-los e solucioná-los.

Os alunos aprenderão a aplicar o método científico a um formulário estruturado de solução de problemas. Essa abordagem é usada para solucionar vários tipos de problemas, incluindo aqueles na inicialização, hardware, armazenamento, RPM, rede, aplicações de terceiros, segurança e kernel. No final do curso, os alunos poderão realizar revisões abrangentes em laboratórios para testar as habilidades adquiridas.

Este curso é baseado no Red Hat Enterprise Linux 8.4.

Após a conclusão do curso, o acesso prático ao laboratório permanecerá disponível por até 45 dias para qualquer curso presencial que inclua um ambiente virtual.

*Observação:* este curso é oferecido como uma aula virtual de cinco dias ou no ritmo que você preferir. As durações podem variar de acordo com a entrega. Para conferir todos os detalhes, a programação e os preços do curso, selecione a localização e clique em "Registre-se" no menu à direita.

[.big]#*Resumo do conteúdo*#

* Utilização do método científico como abordagem para solucionar problemas
* Solução de problemas de inicialização
* Solução de problemas de segurança
* Solucionar problemas de armazenamento
* Solução de problemas de rede

[.big]#*Público-alvo*#

O curso Red Hat Enterprise Linux Diagnostics and Troubleshooting destina-se a administradores de sistemas seniores que desejam aprender mais sobre solução de problemas.

[.big]#*Pré-requisitos do curso*#

A Red Hat faz as seguintes recomendações:

* Ter recebido a certificação https://www.redhat.com/certification/rhcsa[Red Hat Certified System Administrator (RHCSA)] ou experiência profissional semelhante
* Recomenda-se que os alunos tenham certificação https://www.redhat.com/certification/rhce[Red Hat Certified Engineer (RHCE)] ou experiência semelhante

[.big]#*Requisitos técnicos*#

* Para aprendizado virtual, em ritmo próprio, ou treinamento presencial:
** É necessário ter acesso à internet.
** Os laboratórios são realizados no ambiente de aprendizado online da Red Hat.
** Para treinamento presencial, a Red Hat fornecerá um ambiente de curso instalado localmente como alternativa no futuro.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/rh342-red-hat-enterprise-linux-diagnostics-and-troubleshooting
