// Este arquivo é mantido executando scripts/refresh-training.py script

= Red Hat Security: Identity Management and Authentication (RH362)

Aprenda a proteger serviços gerenciamento centralizado de identidades para coordenar a autenticação e autorização de usuários em sistemas clientes, serviços de rede e domínios do Windows.

[.big]#*Descrição do curso*#

No curso Red Hat Security: Identity Management and Authentication (RH362), você aprende a configurar e gerenciar o Identity Management (IdM), um componente completo de gerenciamento de identidades que faz parte do Red Hat Enterprise Linux. Você vai adquirir as habilidades mais exigidas pelos clientes no uso dessa tecnologia.

Alguns dos tópicos abordados no curso são: gerenciamento central e provisionamento de contas de usuário; design e instalação de topologias de servidor do IdM; operação de serviços integrados de autoridade de certificação de TLS e DNS; gerenciamento de autenticação de dois fatores. autenticação por cartão inteligente e operação como provedor de single sign-on; integração e gerenciamento de relações de confiança bidirecionais com o Active Directory e solução de problemas e planejamento de recuperação de desastres. O curso também discute o registro de clientes Linux no IdM e a operação em ambientes empresariais que usam clientes e servidores Linux e Microsoft Windows.

Após a conclusão do curso, o acesso prático ao laboratório permanecerá disponível por até 45 dias para qualquer curso presencial que inclua um ambiente virtual.

*Observação:* este curso é oferecido como aulas virtuais de cinco dias. As durações podem variar de acordo com a entrega. Para conferir todos os detalhes, a programação e os preços do curso, selecione a localização e clique em "Registre-se" no menu à direita.

[.big]#*Resumo do conteúdo do curso*#

* Projetar uma topologia do Identity Management que ofereça escalabilidade e resiliência.
* Descrever as principais tecnologias usadas pelo IdM, incluindo SSSD, PAM, Kerberos e PKI.
* Instalar servidores, réplicas e clientes do Identity Management (IdM) usando playbooks do Ansible.
* Gerenciar serviços do IdM, incluindo autoridade de certificação e DNS integrados.
* Configurar e gerenciar a autenticação do Kerberos e proteger serviços.
* Configurar e gerenciar certificados TLS.
* Criar e gerenciar uma relação de confiança com o Microsoft Active Directory.
* Definir configurações para proteger a autenticação de usuários, incluindo a autenticação de dois fatores e single sign-on.
* Configurar e gerenciar políticas de Sudo, HBAC e RBAC.
* Gerenciar segredos, cofres, certificados e chaves.
* Solucionar problemas de gerenciamento de identidades.
* Integrar o Satellite 6 e o Red Hat Ansible Automation Platform ao IdM.
* Configurar o backup e a recuperação do IdM.

[.big]#*Público-alvo*#

* Profissionais com a certificação Red Hat Certified System Engineer (RHCE) que querem aprender como provisionar e configurar soluções centralizadas de gerenciamento de identidades para clientes Linux e como integrá-las a serviços de rede e outros sistemas desse tipo.
** Especialistas ou engenheiros de gerenciamento de identidades
** Especialistas ou engenheiros de gerenciamento de acesso

[.big]#*Treinamentos recomendados*#

* https://www.redhat.com/rhtapps/assessment/[Faça nossa avaliação gratuita] para saber se esta é a melhor opção para as suas habilidades.
* A certificação RHCE ou habilidade equivalente é pré-requisito para este curso.

[.big]#*Requisitos técnicos*#

* Para aprendizado virtual, em ritmo próprio, ou treinamento presencial:
** É necessário ter acesso à internet.
** Os laboratórios são realizados no ambiente de aprendizado online da Red Hat.
** Para treinamento presencial, a Red Hat fornecerá um ambiente de curso instalado localmente como alternativa no futuro.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/rh362-red-hat-security-identity-management-and-authentication
