// Este arquivo é mantido executando scripts/refresh-training.py script

= Red Hat Satellite 6 Administration (RH403)

[.big]#*Descrição do curso*#

*Aprenda como configurar o Red Hat Satellite 6 para implantar e gerenciar sistemas e software do Red Hat Enterprise Linux*

O Red Hat Satellite 6 Administration (RH403) é um curso baseado em laboratório que explora os conceitos e métodos necessários para um gerenciamento em larga escala bem-sucedido dos sistemas Red Hat® Enterprise Linux®. Você aprenderá a configurar o Red Hat Satellite 6 em um servidor e preenchê-lo com pacotes de software. Você usará o Red Hat Satellite para configurar e gerenciar o ciclo de vida de desenvolvimento do software de um host assinado. Além disso, você aprenderá a provisionar hosts integrados com software e gerenciar a configuração do Ansible® após a implantação.

Este curso é baseado no Red Hat Enterprise Linux 8 e no Red Hat Satellite 6.15.

Após a conclusão do curso, você terá 45 dias de acesso prolongado aos laboratórios hands-on para fazer qualquer curso que inclua um ambiente virtual.

*Observação:* este curso é oferecido como uma aula virtual de cinco dias ou no ritmo que você preferir. As durações podem variar de acordo com a entrega. Para conferir todos os detalhes, a programação e os preços do curso, selecione a localização e clique em "Registre-se" no menu à direita.

[.big]#*Resumo do conteúdo*#

* Verificação de uma instalação do Red Hat Satellite 6.15.
* Ajuste do Red Hat Satellite de acordo com organizações, locais, usuários e funções.
* Gerenciamento de software com ambientes e visualizações de conteúdo do Red Hat Satellite.
* Uso do Red Hat Satellite para configurar hosts com funções e playbooks do Ansible.
* Provisionamento de hosts com software integrado e gerenciamento de configuração.
* Implementação de uma solução de Metal como Serviço (MaaS) com detecção do Satellite e provisionamento de hosts não provisionados.

[.big]#*Público-alvo*#

* Administradores de sistemas Red Hat Enterprise Linux seniores que são responsáveis pelo gerenciamento de diversos servidores e empresas de nuvem híbrida até uma escala enorme

[.big]#*Recomendações para o curso*#

* Ter uma certificação https://www.redhat.com/pt-br/services/certification/rhce[Red Hat Certified Engineer (RHCE)] ou experiência equivalente.
* É recomendado que os candidatos tenham familiaridade com o Red Hat Satellite 6. No entanto, isso não é obrigatório.

[.big]#*Requisitos técnicos*#

* Para aprendizado virtual, em ritmo próprio, ou treinamento presencial:
** É necessário ter acesso à internet.
** Os laboratórios são realizados no ambiente de aprendizado online da Red Hat.
** Para treinamento presencial, a Red Hat fornecerá um ambiente de curso instalado localmente como alternativa no futuro.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/rh403-red-hat-satellite-6-administration
