// Este arquivo é mantido executando scripts/refresh-training.py script

= Red Hat Transformational Learning: Introduction to Pragmatic Site Reliability Engineering (TL112)

[.big]#*Descrição do curso*#

*Uma introdução pragmática à implementação de DevOps da engenharia de confiabilidade de sites*

Red Hat Transformational Learning: Introduction to Pragmatic Site Reliability Engineering (TL112) ensina o vocabulário, os conceitos e as considerações culturais necessários para se preparar para adotar uma implementação de DevOps chamada de engenharia de confiabilidade de sites (SRE). Neste curso, a história, as definições e a abordagem específica da Red Hat sobre essa prática são abordadas enquanto o aluno se prepara para continuar a trajetória de aprendizagem de ingressar ou implementar uma equipe de SRE.

Após a conclusão do curso, o acesso prático ao laboratório permanecerá disponível por até 45 dias para qualquer curso presencial que inclua um ambiente virtual.

*Observação*: este curso é individualizado. As durações podem variar de acordo com a entrega. Para obter detalhes completos, programação e preços do curso, selecione sua localização e "Registre-se" no menu à direita.

[.big]#*Resumo do conteúdo*#

* Introdução à engenharia de confiabilidade de sites
* Determinação da prontidão operacional
* Descrição do esforço excessivo e implementação da automação
* Explicação e cálculo dos orçamentos de erro
* Explicação do gerenciamento de incidentes
* Implementação da engenharia de confiabilidade de sites

[.big]#*Público-alvo*#

* Profissionais de DevOps
* Administradores de sistemas
* Desenvolvedores de software

[.big]#*Pré-requisitos do curso*#

* Não há pré-requisitos para este curso.

[.big]#*Requisitos técnicos*#

* Somente livro do curso, não há laboratórios hands-on

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/tl112-pragmatic-introduction-site-reliability-engineering-implementation-devops
