// Este arquivo é mantido executando scripts/refresh-training.py script

= Red Hat Training: Open Practices for your DevOps Journey (TL250)

[.big]#*Descrição do curso*#

*Descubra práticas abertas para fazer mudanças gradativas nos processos e facilitar sua jornada de transformação para o DevOps.*

O curso Open Practices for your DevOps Journey (TL250) prepara o aluno para facilitar e participar da descoberta, planejamento e entrega de projetos em que a transformação para DevOps é desejada. No final do curso, você criará um conjunto de práticas selecionadas e poderá repensar sua abordagem em projetos de várias equipes diferentes. Com as novas habilidades, você ajudará sua organização a descobrir efetivamente a finalidade da equipe, alinhar-se com as opções do projeto e entregar valor, alcançando os resultados desejados.

Após a conclusão do curso, o acesso prático ao laboratório permanecerá disponível por até 45 dias para qualquer curso presencial que inclua um ambiente virtual.

*Observação*: este curso é individualizado. As durações podem variar de acordo com a entrega. Para conferir todos os detalhes, a programação e os preços do curso, selecione a localização e clique em "Registre-se" no menu à direita.

[.big]#*Resumo do conteúdo*#

* Práticas de descoberta que favorecem o alinhamento sobre o que se deseja criar e quem será responsável pelas tarefas.
* Práticas de entrega que favorecem a criação de meios rápidos e eficazes de entregar resultados e refletir.
* Práticas que favorecem opções e dão suporte à priorização e organização do trabalho a ser realizado logicamente.
* Práticas fundamentais em equipe que favorecem a colaboração e a comunicação, além de conceitos técnicos.
* Como visualizar o trabalho e colaborar remotamente de maneira compatível com os métodos de entrega de DevOps.

[.big]#*Público-alvo*#

* Gerentes de projetos, instrutores de abordagens ágeis, especialistas em Scrum: pessoas que facilitam o planejamento e a execução de projetos e desejam ajustar a abordagem, além de ajudar a organização a fazer a transição para DevOps.
* Administradores de sistema, SRE, desenvolvedores de aplicações: membros da equipe de projetos técnicos que participam das fases de descoberta, planejamento e execução poderão acelerar a conclusão dessas práticas com mais detalhes.
* Liderança, proprietários de soluções e principais stakeholders: indivíduos com interesse no sucesso do projeto ou que oferecem supervisão, objetivos e metas terão uma melhor percepção do processo e garantirão que seus requisitos sejam observados.

[.big]#*Treinamentos recomendados*#

* Não há pré-requisitos para este curso.

[.big]#*Requisitos técnicos*#

* Este curso não tem laboratórios associados, mas pode exigir o uso de um navegador da Internet para acessar várias ferramentas de colaboração, como Miro ou Trello.

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/red-hat-training-open-practices-your-devops-journey-tl250
