// Este arquivo é mantido executando scripts/refresh-training.py script

= Red Hat Training: DevOps Culture and Practice Enablement (TL500)

[.big]#*Experimente as possibilidades do DevOps por meio de práticas e cultura open source comprovadas usadas pela Red Hat para oferecer suporte à inovação do cliente*#

O Red Hat Training: DevOps Culture and Practice Enablement (TL500) é um curso imersivo de cinco dias que oferece aos estudantes a oportunidade de vivenciar e implementar as mudanças culturais necessárias em muitas jornadas de adoção eficaz do DevOps. Muitas ofertas de treinamento ágil se concentram em uma framework específica, mecanismo de entrega ou tecnologia. Em vez disso, a DevOps Culture and Practice combina as melhores ferramentas de muitas das principais frameworks para combinar descoberta e entrega contínuas com práticas culturais e técnicas em uma experiência única e altamente envolvente que simula cenários e aplicações do mundo real.

Para alcançar os objetivos de aprendizagem, os participantes devem incluir várias funções de uma organização. Os proprietários de soluções corporativas, arquitetos, desenvolvedores e engenheiros de confiabilidade de sites ganharão a experiência de trabalhar fora de seus silos tradicionais. A rotina diária simula uma equipe de entrega do mundo real, onde equipes multifuncionais aprendem como a colaboração gera inovação. Munidos de experiências compartilhadas e práticas recomendadas, a equipe poderá aplicar o que aprendeu para ajudar positivamente a cultura e a missão da empresa em busca de novos projetos e processos aprimorados.

Este curso inclui uma cópia do livro do curso Red Hat Training: Open Practices for your DevOps Journey, que pode ser usado como um recurso à medida que os alunos aprendem neste curso e os aplicam a outros cenários do mundo real.

*Observação:* este curso tem duração de cinco dias. As durações podem variar de acordo com a entrega. Para obter detalhes completos, programação e preços do curso, selecione sua localização e "Registre-se" no menu à direita.

[.big]#*O que esse curso tem de diferente de qualquer outro treinamento técnico DevOps ou Ágil?*#

* A maioria dos treinamentos Ágil disponíveis se concentra em um framework específico ou na entrega ou tecnologia. Nosso curso combina as melhores ferramentas de vários frameworks de destaque.
* Este curso combina descoberta e entrega contínuas com práticas culturais e técnicas em uma experiência única e envolvente, repleta de aplicações do mundo real. Você aprenderá as práticas individuais e como cada uma se baseia na próxima para melhorar o alinhamento e a eficiência da entrega.
* Alguns treinamentos técnicos de DevOps se concentram unicamente na implementação da tecnologia para realizar tarefas específicas, não em como essa tecnologia se integra e permite a entrega de muitas funcionalidades e correções de bugs de que os clientes precisam. Esta aula incentiva uma abordagem de pensamento sistêmico para a entrega.

[.big]#*Quem deve participar?*#

Essa experiência demonstra como os indivíduos em diferentes funções devem aprender a compartilhar, colaborar e trabalhar em prol de um objetivo comum para alcançar resultados positivos e impulsionar a inovação. Os proprietários de soluções de negócios, desenvolvedores, engenheiros de confiabilidade de sites e engenheiros se beneficiarão especialmente ao experimentar esse cenário, que inclui alguns aspectos técnicos que dependem do trabalho com sistemas de software. Você saberá como dar valor contínuo aos clientes por meio de uma compreensão aprimorada das necessidades em constante mudança dos clientes e da capacidade de obter novas ideias mais rapidamente para o mercado. Nossos instrutores compartilharão experiências e práticas recomendadas aprendidas ao interagir diretamente com os clientes durante compromissos de serviços da Red Hat.

[.big]#*Quais são os pré-requisitos?*#

* É útil conhecer práticas e princípios ágeis
* É vantajoso ter experiência com o uso de práticas e metodologias ágeis, como o scrum

[.big]#*Requisitos técnicos*#

* É necessário ter conexão com a Internet para acessar determinados sites (AWS, YouTube, Google Drive e bate-papo)
* Este curso exige que você "traga sua própria estação de trabalho de desenvolvedor" (https://www.redhat.com/pt-br/resources/red-hat-training-and-certification-classroom-requirements[BYDW]), então traga seu próprio dispositivo
* O navegador Chrome é sugerido

Para mais detalhes ou para se inscrever:
https://www.redhat.com/pt-br/services/training/tl500-devops-culture-and-practice-enablement
